server:
  port: 8088

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/online_store?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=GMT%2B8
    username: root
    password: Aa941211
    type: com.zaxxer.hikari.HikariDataSource

config:
  FACE_FOLDER: /Users/darvis/Documents/upload/face/