server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: 20MB
  max-http-header-size: 81920

spring:
  profiles:
    active: prod
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB




